### PR TITLE
adding testing files to test binoc github action

### PR DESCRIPTION
**Pull request by vsoch**
This is a work in progress to test the binoc GitHub action! I've added a few spack packages to the repo here, and (to start) I'm specifying the GitHub actions users for the bot, since the opened PRs don't need to trigger any additional actions.

Signed-off-by: vsoch <vsoch@users.noreply.github.com>

### CODE REVIEW

**Comment by vsoch** [comment]
@alecbcs does the output here look correct to you?

```
  ____  _                  
| __ )(_)_ __   ___   ___ 
|  _ \| | '_ \ / _ \ / __|
| |_) | | | | | (_) | (__ 
|____/|_|_| |_|\___/ \___|
Application Version: v0.1.0

[Parsing Container Blueprints]
[Checking Containers for Updates]
```
Maybe there should be a message like [No updates were found for x packages] so we can distinguish between "it ran and finished" and "it started running and I'm not sure if it finished."

**Comment by alecbcs** [comment]
@vsoch Adding a scan results report at the end is a fantastic idea!

**Comment by alecbcs** [comment]
@vsoch I just re-ran Binoc on this repository after adding the Scan Report to v0.0.4 and it looks like it's finding the packages just none of them are out-of-date.
```
  ____  _                  
| __ )(_)_ __   ___   ___ 
|  _ \| | '_ \ / _ \ / __|
| |_) | | | | | (_) | (__ 
|____/|_|_| |_|\___/ \___|
Application Version: v0.1.0

[Parsing Container Blueprints]
[Checking Containers for Updates]

[Scan Results]
4     Packages Parsed
0     Packages Updated
0     Packages Skipped
````

**Comment by alecbcs** [comment]
Ahh okay, so I was still confused why Singularity didn't trigger an update but taking a look at it, it's got a `master` version tag which `go-parspack` doesn't yet know what to do with. I'm presuming we should treat branch name versions as not a "real" version but keep them in the array of versions? What do you think?

**Comment by vsoch** [comment]
Yep that makes sense 👍

**Comment by alecbcs** [comment]
Cool! Otherwise all of this looks good to me to merge.

**Pull request merged**
