### PR TITLE
Update binoc.yml to use GitHub Secret Keys

### PR DESCRIPTION
**Pull request by alecbcs**
Checking to make sure I set up the Binoc Secrets correctly this morning!

### CODE REVIEW

**Comment by alecbcs** [comment]
@vsoch I think this is ready to go but I didn't want to merge it without looping you in.

**Comment by vsoch** [comment]
Do you want to add a `pull_request: []` trigger to see it run (and then we can remove?) If you think it's fairly straight forward and want to wait to test for when the action runs, that works for me too (I do both).

**Review by vsoch — APPROVED** [review]

**Comment by vsoch** [comment]
I'm good with testing when it runs! I think this fix is fairly straight forward. Let's merge!

**Comment by vsoch** [comment]
I realize you did run it and I'm just slow and missed it :laughing: 

https://github.com/autamus/spacktainer-registry/runs/2010267619

**Comment by alecbcs** [comment]
> I realize you did run it and I'm just slow and missed it laughing
> 
> https://github.com/autamus/spacktainer-registry/runs/2010267619

Haha no worries, I'm sneaky!

**Pull request merged**
